### ISSUE TITLE
display node_label

### ISSUE THREAD

**Issue by fabiandrft** [medialab/ipysigma#223] opened 2024-04-09 18:08 UTC
Is it possible to manually decide which node labels to display? It would be great to add (and display) labels manually.
Thank you.

**Comment by Yomguithereal** [comment] 2024-04-10 08:48
@fabiandrft this is a good idea indeed and will be implemented in the future through a `force_node_labels` kwarg. But since this issue is a duplicate of #128 I will close this issue now :)

**Closed by Yomguithereal** 2024-04-10 08:48 UTC
